### ISSUE TITLE
Allow to add quotes into stringLiteral parameters

### ISSUE THREAD

**Issue by supakonoha** [vapor/leaf-kit#122]
**Is your feature request related to a problem? Please describe.**
I'm using a custom tag that has a string parameter. If this parameter includes a quote, this is interpreted as final quote for the parameter, although it's escaped. For example:

`#tag("value", "this is a \"custom\" parameter")`

for the second parameter, **LeafLexer** parses it as `this is a \` instead of `this is "custom" parameter` 

**Describe the solution you'd like**
I would like to allow quotes inside parameters using escape characters or other option.

**Comment by roya1v** [comment]
As far as I see when we read a string we do not distinguish between quotes that were and were not escaped.
That's why I looked at escaping them using a different character and create a draft #124  of how it could work escaping it like `$\` but it should work with any other character too.
Let me know what you think!

**Comment by supakonoha** [comment]
Looks nice!!!!! Thanks for this change!!!!

Just a suggestion, I don't know if we could define "$" as constant or add into enum with .quote?
