### ISSUE TITLE
free parsing of `#` 

### ISSUE THREAD

**Issue by loganwright** [vapor/leaf-kit#16]
in prior versions of leaf, the following was supported:

```
#("hi") #thisIsNotATag...
```

currently tho, there's no way to distinguish that it is not a tag given new parsing rules, particularly around end tags.

we could propose to use the original `#("#")` but is maybe not so nice long term. alternatives could be found to support this type of syntax more intelligently if we can design rules to do so.

**Comment by tdotclare** [comment]
I intend to solve this in parser next. The easiest solution is to simply query available tags and automatically dump to raw if none exists, but this does face a small problem in the sense that templates are decoupled from the LeafKit API user. A third party could produce templates using tags that are dependent on a specific USE of LeafKit, so lack of a tag availability in one application does not mean that the template is necessarily intending to treat it as `raw`, and so using it and decaying to `raw` on an application without the tag theoretically could expose internal code. This isn't possible to control without some sort of tag definition within the template itself, which is thoroughly undesirable in my opinion. However, this is definitely an edge case and convenience would certainly lean towards just converting to `raw`.

I'd be in favor of something like a strictness level for parsing, so that where gracefully decaying appears to be dangerous - eg `#isThisATag(true)` which seems to be a tag with parameters, serializing would fail in both strict and lax mode, and when it appears safe - eg `#isThisATag` which seems to be a tag with no params or body - strict would still error but lax would decay to raw.

**Comment by tdotclare** [comment]
Closed in LeafKit-1.0.0tau
